# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupname',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
