# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-09 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlog', '0010_remove_control_nokeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='nokeyword',
            field=models.TextField(null=True),
        ),
    ]
